# Generated by Django 5.1.6 on 2025-05-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the uploaded file",
                        max_length=150,
                        unique=True,
                        verbose_name="Uploaded File Name",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Text file",
                        null=True,
                        upload_to="text_files/",
                        verbose_name="Uploaded Text File",
                    ),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
            },
        ),
    ]
